// generated by gen_cnn_rtl.py -- do not edit
localparam integer NL = 4;
localparam integer NIN = 32;
localparam integer ABUF_DEPTH = 1568;
localparam integer AW = 11;
localparam integer WDEPTH = 657;
localparam integer WAW = 10;
localparam integer PQDEPTH = 128;
localparam integer PQAW = 7;
localparam integer TW = 9;
localparam integer LANES_GEN = 32;
function integer L_K; input integer l; begin case (l)
    0: L_K = 5;
    1: L_K = 5;
    2: L_K = 1;
    3: L_K = 1;
    default: L_K = 0; endcase end endfunction
function integer L_Cin; input integer l; begin case (l)
    0: L_Cin = 1;
    1: L_Cin = 8;
    2: L_Cin = 400;
    3: L_Cin = 32;
    default: L_Cin = 0; endcase end endfunction
function integer L_Cout; input integer l; begin case (l)
    0: L_Cout = 8;
    1: L_Cout = 16;
    2: L_Cout = 32;
    3: L_Cout = 1;
    default: L_Cout = 0; endcase end endfunction
function integer L_Hin; input integer l; begin case (l)
    0: L_Hin = 32;
    1: L_Hin = 14;
    2: L_Hin = 1;
    3: L_Hin = 1;
    default: L_Hin = 0; endcase end endfunction
function integer L_Win; input integer l; begin case (l)
    0: L_Win = 32;
    1: L_Win = 14;
    2: L_Win = 1;
    3: L_Win = 1;
    default: L_Win = 0; endcase end endfunction
function integer L_GH; input integer l; begin case (l)
    0: L_GH = 14;
    1: L_GH = 5;
    2: L_GH = 1;
    3: L_GH = 1;
    default: L_GH = 0; endcase end endfunction
function integer L_GW; input integer l; begin case (l)
    0: L_GW = 14;
    1: L_GW = 5;
    2: L_GW = 1;
    3: L_GW = 1;
    default: L_GW = 0; endcase end endfunction
function integer L_pool; input integer l; begin case (l)
    0: L_pool = 1;
    1: L_pool = 1;
    2: L_pool = 0;
    3: L_pool = 0;
    default: L_pool = 0; endcase end endfunction
function integer L_relu; input integer l; begin case (l)
    0: L_relu = 1;
    1: L_relu = 1;
    2: L_relu = 1;
    3: L_relu = 0;
    default: L_relu = 0; endcase end endfunction
function integer L_S; input integer l; begin case (l)
    0: L_S = 20;
    1: L_S = 23;
    2: L_S = 23;
    3: L_S = 0;
    default: L_S = 0; endcase end endfunction
function integer L_T; input integer l; begin case (l)
    0: L_T = 25;
    1: L_T = 200;
    2: L_T = 400;
    3: L_T = 32;
    default: L_T = 0; endcase end endfunction
function integer L_G; input integer l; begin case (l)
    0: L_G = 1;
    1: L_G = 1;
    2: L_G = 1;
    3: L_G = 1;
    default: L_G = 0; endcase end endfunction
function integer L_WBASE; input integer l; begin case (l)
    0: L_WBASE = 0;
    1: L_WBASE = 25;
    2: L_WBASE = 225;
    3: L_WBASE = 625;
    default: L_WBASE = 0; endcase end endfunction
function integer L_PBASE; input integer l; begin case (l)
    0: L_PBASE = 0;
    1: L_PBASE = 32;
    2: L_PBASE = 64;
    3: L_PBASE = 96;
    default: L_PBASE = 0; endcase end endfunction
function integer L_OUT_HW; input integer l; begin case (l)
    0: L_OUT_HW = 196;
    1: L_OUT_HW = 25;
    2: L_OUT_HW = 1;
    3: L_OUT_HW = 1;
    default: L_OUT_HW = 0; endcase end endfunction
function integer L_STEP_X; input integer l; begin case (l)
    0: L_STEP_X = 2;
    1: L_STEP_X = 2;
    2: L_STEP_X = 1;
    3: L_STEP_X = 1;
    default: L_STEP_X = 0; endcase end endfunction
function integer L_STEP_ROW; input integer l; begin case (l)
    0: L_STEP_ROW = 38;
    1: L_STEP_ROW = 20;
    2: L_STEP_ROW = 1;
    3: L_STEP_ROW = 1;
    default: L_STEP_ROW = 0; endcase end endfunction
function integer L_INC_KY; input integer l; begin case (l)
    0: L_INC_KY = 28;
    1: L_INC_KY = 10;
    2: L_INC_KY = 1;
    3: L_INC_KY = 1;
    default: L_INC_KY = 0; endcase end endfunction
function integer L_INC_CI; input integer l; begin case (l)
    0: L_INC_CI = 892;
    1: L_INC_CI = 136;
    2: L_INC_CI = 1;
    3: L_INC_CI = 1;
    default: L_INC_CI = 0; endcase end endfunction
function integer L_SP2; input integer l; begin case (l)
    0: L_SP2 = 31;
    1: L_SP2 = 13;
    2: L_SP2 = 0;
    3: L_SP2 = 0;
    default: L_SP2 = 0; endcase end endfunction
