# -*- coding: utf-8 -*-
"""Turn an exported INT8 model (cnn/quant_hw.py --export) into the RTL inputs of
cnn_core.v:

    cnn_w.hex   wide weight ROM, one word per (layer, channel-group, tap):
                 word = {lane L-1 ... lane 0}, each lane an int8 weight
    cnn_pq.hex  per (layer, channel): {bias int32, requant multiplier 16b} (48b)
    cnn_cfg.vh  localparams + per-layer functions (shapes, strides, bases, shift)

usage: python gen_cnn_rtl.py <export_dir> <out_dir> --lanes 32
"""
import argparse
import json
import math
import os


def rd_hex(path, bits, signed):
    out = []
    for line in open(path):
        line = line.strip()
        if not line:
            continue
        v = int(line, 16)
        if signed and v >= 1 << (bits - 1):
            v -= 1 << bits
        out.append(v)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("export_dir")
    ap.add_argument("out_dir")
    ap.add_argument("--lanes", type=int, default=32)
    a = ap.parse_args()
    L = a.lanes
    man = json.load(open(os.path.join(a.export_dir, "manifest.json")))
    nin = man["net_input"]
    os.makedirs(a.out_dir, exist_ok=True)

    layers = []
    cur_c, cur_h = 1, nin
    wwords, pqwords = [], []
    wbase = pbase = 0
    max_act = nin * nin
    est_cycles = 0
    for i, ent in enumerate(man["layers"]):
        base = ent["name"]
        W = rd_hex(os.path.join(a.export_dir, base + "_w.hex"), 8, True)
        bias = rd_hex(os.path.join(a.export_dir, base + "_b.hex"), 32, True)
        shp = ent["W_shape"]
        pool, relu = int(ent["pool"]), int(ent["relu"])
        if ent["kind"] == "conv":
            cout, cin, k, _ = shp
            assert cin == cur_c, (i, cin, cur_c)
            hin = win = cur_h
            hout = wout = hin - k + 1
            T = cin * k * k
            hw_in = hin * win
        else:
            cout, cflat = shp
            assert cflat == cur_c * cur_h * cur_h, (i, cflat, cur_c, cur_h)
            k, cin, hin, win, hout, wout = 1, cflat, 1, 1, 1, 1
            T = cflat
            hw_in = 1
        if pool:
            gh, gw = hout // 2, wout // 2
        else:
            gh, gw = hout, wout
        out_hw = gh * gw
        G = math.ceil(cout / L)
        if pool:
            step_x, step_row = 2, 2 * win - 2 * (gw - 1)
        else:
            step_x, step_row = 1, win - wout + 1
        inc_ky = win - (k - 1)
        inc_ci = hw_in - (k - 1) * win - (k - 1)
        M = rd_hex(os.path.join(a.export_dir, base + "_m.hex"), 16, False) if relu else [0] * cout
        shift = ent.get("shift", 0) or 0
        # weight words: [g][t] -> lanes
        for g in range(G):
            for t in range(T):
                word = 0
                for l in range(L):
                    ch = g * L + l
                    v = W[ch * T + t] if ch < cout else 0
                    word |= (v & 0xFF) << (8 * l)
                wwords.append(word)
        for g in range(G):
            for l in range(L):
                ch = g * L + l
                b = bias[ch] if ch < cout else 0
                m = M[ch] if ch < cout else 0
                pqwords.append(((b & 0xFFFFFFFF) << 16) | (m & 0xFFFF))
        npix = gh * gw * (4 if pool else 1)
        est_cycles += G * npix * T
        layers.append(dict(kind=0 if ent["kind"] == "conv" else 1, K=k, Cin=cin, Cout=cout, Hin=hin, Win=win,
                           Hout=hout, Wout=wout, GH=gh, GW=gw, pool=pool, relu=relu, S=shift, T=T, G=G,
                           WBASE=wbase, PBASE=pbase, OUT_HW=out_hw, STEP_X=step_x, STEP_ROW=step_row,
                           INC_KY=inc_ky, INC_CI=inc_ci, SP2=win - 1, HWIN=hw_in))
        wbase += G * T
        pbase += G * L
        max_act = max(max_act, cout * out_hw)
        cur_c, cur_h = cout, (gh if cout and ent["kind"] == "conv" else 1)
        if ent["kind"] == "conv":
            cur_h = gh
        else:
            cur_h = 1
    assert layers[-1]["relu"] == 0 and layers[-1]["Cout"] == 1, "last layer must be the single-logit FC"

    wdepth, pqdepth = wbase, pbase
    aw = max(1, math.ceil(math.log2(max_act)))
    waw = max(1, math.ceil(math.log2(wdepth)))
    pqaw = max(1, math.ceil(math.log2(pqdepth)))
    maxt = max(l["T"] for l in layers)
    tw = max(1, math.ceil(math.log2(maxt + 1)))

    with open(os.path.join(a.out_dir, "cnn_w.hex"), "w") as f:
        for w in wwords:
            f.write(format(w, "0%dx" % (L * 2)) + "\n")
    with open(os.path.join(a.out_dir, "cnn_pq.hex"), "w") as f:
        for w in pqwords:
            f.write(format(w, "012x") + "\n")

    fields = ["K", "Cin", "Cout", "Hin", "Win", "GH", "GW", "pool", "relu", "S", "T", "G", "WBASE", "PBASE",
              "OUT_HW", "STEP_X", "STEP_ROW", "INC_KY", "INC_CI", "SP2"]
    lines = ["// generated by gen_cnn_rtl.py -- do not edit",
             f"localparam integer NL = {len(layers)};",
             f"localparam integer NIN = {nin};",
             f"localparam integer ABUF_DEPTH = {max_act};",
             f"localparam integer AW = {aw};",
             f"localparam integer WDEPTH = {wdepth};",
             f"localparam integer WAW = {waw};",
             f"localparam integer PQDEPTH = {pqdepth};",
             f"localparam integer PQAW = {pqaw};",
             f"localparam integer TW = {tw};",
             f"localparam integer LANES_GEN = {L};"]
    for fld in fields:
        lines.append(f"function integer L_{fld}; input integer l; begin case (l)")
        for i, ly in enumerate(layers):
            lines.append(f"    {i}: L_{fld} = {ly[fld]};")
        lines.append(f"    default: L_{fld} = 0; endcase end endfunction")
    open(os.path.join(a.out_dir, "cnn_cfg.vh"), "w").write("\n".join(lines) + "\n")

    summ = dict(lanes=L, layers=layers, weight_words=wdepth, weight_bits=wdepth * L * 8, pq_words=pqdepth,
                max_act_bytes=max_act, est_issue_cycles=est_cycles)
    json.dump(summ, open(os.path.join(a.out_dir, "cnn_params.json"), "w"), indent=1)
    print(f"{len(layers)} layers, L={L}: weight ROM {wdepth} x {L*8}b ({wdepth*L*8/1024:.0f} Kb), pq ROM {pqdepth} x 48b, "
          f"act buffer {max_act} B, ~{est_cycles} MAC-issue cycles/patch")


if __name__ == "__main__":
    main()
