function audit_recip_precision(varargin)
%AUDIT_RECIP_PRECISION  Checklist section 1.4: sweep the reciprocal-multiply
%   constant M against exact arithmetic instead of guessing it.
%
%   AUDIT_RECIP_PRECISION()
%
%   The fixed-point front end never divides by N at run time. It multiplies by
%   a precomputed constant:
%
%       invN = <2^M / N>            (computed once, offline)
%       m1   = round(S1 * invN / 2^M)
%
%   fixedpoint_config.m sets M = 24 with an analytic justification
%   ("~6e-8 relative, far below every downstream LUT's resolution"). The FPGA
%   checklist section 1.4 says explicitly not to do that:
%
%       "INV_N = (1<<M)/N truncates. At M=16, N=40 this produced the wrong
%        rounding direction on ~84% of inputs, all biased the same way.
%        M=24 reduced it to ~2.5%. Sweep M against exact-fraction arithmetic
%        before picking it -- don't guess."
%
%   This script runs that sweep. It checks TWO things the analytic argument
%   does not cover:
%
%   1. HOW the constant is formed. MATLAB's round(2^M/N) is round-to-nearest;
%      a Verilog `(1<<M)/N` expression TRUNCATES. If the RTL computes the
%      constant itself rather than taking the one this project generates, the
%      two models use different constants and the golden reference stops being
%      golden. Both are swept here so the difference is measured, not assumed.
%
%   2. The BIAS, not just the error magnitude. A reciprocal-multiply error that
%      is small but always the same sign accumulates into a systematic
%      threshold offset, which is far worse for a detector than a larger
%      symmetric error.
%
%   Checklist section 1.11 is the follow-on rule: a constant needing true
%   round-to-nearest must be precomputed offline and hardcoded in the RTL,
%   with a comment naming the script that generated it. That script is this
%   one -- it prints the exact Verilog localparam lines to paste.

p = inputParser;
addParameter(p, 'Geometries', [17 13; 21 15; 15 11; 31 21]);
addParameter(p, 'MList',      [16 18 20 22 24 26 28]);
addParameter(p, 'NumTrials',  2e6);
parse(p, varargin{:});

G  = p.Results.Geometries;
ML = p.Results.MList;
nT = p.Results.NumTrials;

fprintf('=====================================================================\n');
fprintf(' Reciprocal-multiply precision audit  (FPGA checklist section 1.4)\n');
fprintf('=====================================================================\n');

rng(20260912);

for gi = 1:size(G,1)
    sli = G(gi,1); guard = G(gi,2);
    cfg = fixedpoint_config(sli, guard);
    N   = cfg.N;

    % Realistic S1 range: the windowed sum of N centred log-amplitude codes.
    % Sampled uniformly over the full analytic span so the sweep covers the
    % accumulator's whole reachable range, not just the typical part.
    S1max = N * cfg.xc_max * cfg.xc.scale;
    S1 = round((rand(nT,1)*2 - 1) * S1max);

    exact = S1 / N;

    fprintf('\n--- sli=%d guard=%d  ->  N = %d ---\n', sli, guard, N);
    fprintf('  %4s | %-28s | %-28s\n', 'M', 'invN = ROUND(2^M/N)  [MATLAB]', 'invN = FLOOR(2^M/N) [Verilog /]');
    fprintf('  %4s | %10s %8s %7s | %10s %8s %7s\n', ...
        '', 'wrong%', 'maxerr', 'bias', 'wrong%', 'maxerr', 'bias');

    for M = ML
        [wr_r, me_r, bi_r] = eval_const(S1, exact, round(2^M / N), M);
        [wr_f, me_f, bi_f] = eval_const(S1, exact, floor(2^M / N), M);
        fprintf('  %4d | %9.3f%% %8.2e %+7.3f | %9.3f%% %8.2e %+7.3f\n', ...
            M, wr_r, me_r, bi_r, wr_f, me_f, bi_f);
    end

    % ---- The constants this project actually uses -----------------------
    M = cfg.RECIP_M;
    fprintf('\n  IN USE: M = %d\n', M);
    fprintf('    invN   = round(2^%d / %d)     = %d   (floor would give %d)\n', ...
        M, N,   round(2^M/N),   floor(2^M/N));
    fprintf('    invNm1 = round(2^%d / %d)     = %d   (floor would give %d)\n', ...
        M, N-1, round(2^M/(N-1)), floor(2^M/(N-1)));
    if round(2^M/N) ~= floor(2^M/N)
        fprintf('    *** round and floor DIFFER for 1/N at this M. A Verilog\n');
        fprintf('        `(1<<%d)/%d` expression would NOT reproduce this model.\n', M, N);
    else
        fprintf('    (round == floor for 1/N here, but do not rely on it -- see below)\n');
    end
    if round(2^M/(N-1)) ~= floor(2^M/(N-1))
        fprintf('    *** round and floor DIFFER for 1/(N-1) at this M. A Verilog\n');
        fprintf('        `(1<<%d)/%d` expression would NOT reproduce this model.\n', M, N-1);
    end

    fprintf('\n  Verilog constants to HARDCODE (checklist section 1.11) --\n');
    fprintf('  // Generated by _comparison/audit_recip_precision.m -- do NOT\n');
    fprintf('  // write these as (1<<M)/N in Verilog: integer division truncates.\n');
    fprintf('  localparam integer RECIP_M  = %d;\n', M);
    fprintf('  localparam integer INV_N    = %d;  // round(2^%d/%d), N   = %d\n', ...
        round(2^M/N), M, N, N);
    fprintf('  localparam integer INV_NM1  = %d;  // round(2^%d/%d), N-1 = %d\n', ...
        round(2^M/(N-1)), M, N-1, N-1);
    fprintf('  localparam integer K2_MULT  = %d;  // round(N/(N-1)   * 2^%d)\n', ...
        round(cfg.k2_scale * 2^M), M);
    fprintf('  localparam integer K3_MULT  = %d;  // round(N^2/((N-1)(N-2)) * 2^%d)\n', ...
        round(cfg.k3_scale * 2^M), M);
end

fprintf('\n=====================================================================\n');
fprintf(' Reading the table:\n');
fprintf('   wrong%%  = fraction of inputs whose rounded result differs from\n');
fprintf('             round(exact) -- i.e. the reciprocal-multiply picked a\n');
fprintf('             different integer than true division would have.\n');
fprintf('   bias    = mean signed error in LSB. A NON-ZERO BIAS IS THE REAL\n');
fprintf('             HAZARD: it accumulates into a systematic threshold\n');
fprintf('             offset rather than averaging out.\n');
fprintf('=====================================================================\n');
end


function [wrongPct, maxErr, biasLsb] = eval_const(S1, exact, invN, M)
%EVAL_CONST  Compare a reciprocal-multiply against exact division.
    got = S1 .* invN / 2^M;
    err = got - exact;
    wrongPct = 100 * mean(round(got) ~= round(exact));
    maxErr   = max(abs(err));
    biasLsb  = mean(err);
end
