kids.push(H1("5a. Whole data set on the board: Weibull only versus Weibull + CNN"));
kids.push(P(["The context cascade was run on the DE10-Standard over all 5,604 HRSID images (1,015,171 events, every frame bit-exact against the golden models, prescreen 9.01 ms per frame). One sweep gives both systems: ", B("Weibull only"), " accepts every prescreen event; ", B("Weibull + CNN"), " accepts events whose integer logit reaches the threshold, which is applied to the stored logits at the four validation-calibrated values (90 / 95 / 97 / 98 % ship retention on the validation images). The CNN was trained on the train images, so only the test rows are held-out; train and validation rows are in-sample for the CNN (the prescreen has no training). 95 % confidence intervals come from 1,000 bootstrap resamples of images."]));
kids.push(caption("Table 2a. Whole-data-set evaluation of the on-board sweep (context cascade, config A prescreen), by subset."));
const SUBN = { all: "all 5,604", train: "train 3,922", val: "val 840", test: "test 842" };
const sysName = (s) => s.replace("Weibull only (prescreen)", "Weibull only").replace("cascade @ ", "Weibull + CNN @ ").replace(" val retention (theta ", " (theta ");
const T6 = [], hl6 = [];
["all", "train", "val", "test"].forEach((sub) => fsr(sub).forEach((r) => { if (r.system.includes("97 %")) hl6.push(T6.length); T6.push([SUBN[sub], sysName(r.system), ci(100 * r.recall, 100 * r.recall_lo, 100 * r.recall_hi, f1), pc(r.recall_inshore), pc(r.recall_offshore), ci(r.FA_per_img, r.FA_per_img_lo, r.FA_per_img_hi, f2), f3(r.precision), f3(r.F1)]); }));
kids.push(table([1300, 3700, 2500, 1150, 1150, 2600, 1000, 800], ["Subset (images)", "System", "Recall % (95 % CI)", "Inshore %", "Offshore %", "False events / img (95 % CI)", "Precision", "F1"], T6, 15, hl6));
kids.push(note("Recall = ships with at least one accepted event within 4 px of the ship polygon (16,951 ships on all images; 2,877 on the test split). Weibull-only rows: every event accepted, so the false events are all off-ship events and precision is not meaningful as a detector figure. Shaded rows: the 97 % operating point. The test rows reproduce the software evaluation of the INT8 network (96.2 % at 2.64 false events per image at the 97 % target)."));
kids.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 80, after: 40 }, children: [new ImageRun({ type: "png", data: fs.readFileSync(path.resolve(__dirname, "..", "Figures", "fixedpoint_full_sweep.png")), transformation: { width: 900, height: 360 }, altText: { title: "Recall versus false events per image", description: "Whole-data-set and test-split recall against false events per image for the on-board cascade", name: "full sweep" } })] }));
kids.push(note("Figure 1. Recall against false events per image for the on-board cascade, sweeping the CNN threshold over the stored logits (blue: all ships; red dashed: inshore ships); black points are the four validation-calibrated operating points with image-bootstrap 95 % CIs. The Weibull-only system sits at 99.6-99.7 % recall and 166-173 false events per image, far to the right of the plotted range."));
const A97 = fsr("all").find((r) => r.system.includes("97 %")), T97 = fsr("test").find((r) => r.system.includes("97 %")), WA = fsr("all")[0];
kids.push(P([B("Reading Table 2a. "), "The prescreen alone finds ", pc(WA.recall), " % of the 16,951 ships (inshore ", pc(WA.recall_inshore), " %, offshore ", pc(WA.recall_offshore), " %) but leaves ", f1(WA.FA_per_img), " false events per image. The CNN removes about ", (100 * (1 - A97.FA_per_img / WA.FA_per_img)).toFixed(1), " % of them at the 97 % target: ", pc(A97.recall), " % recall at ", f2(A97.FA_per_img), " false events per image on all images, ", pc(T97.recall), " % at ", f2(T97.FA_per_img), " on the held-out test split. The ", f1(100 * (WA.recall - A97.recall)), "-point recall cost on all images is the price of the CNN stage. The test split's confidence intervals are about three times wider than those of the whole data set, and the train, validation and test recalls agree within their intervals at every operating point, so the in-sample rows are not visibly inflated."]));

kids.push(H1("5b. Training statistics: seeds and splits"));
kids.push(P(["The CNN numbers so far came from one seed and one split. Four further INT8 trainings were run for each network (context and single tower) with the identical recipe: two more seeds on the original split (sd2, sd3) and two more splits (split seeds 20261004 and 20261005, training seed 1; sp2, sp3), each with its own validation thresholds and its own held-out test images. Together with the original run (sd1) this gives five runs per network. Table 2b gives mean and standard deviation over the runs, and the image-bootstrap 95 % CI of the original run for reference; Table 2c compares the two networks run by run."]));
kids.push(caption("Table 2b. Test-split results at the validation-calibrated thresholds, mean +- s.d. over the runs (n = number of runs)."));
const T7 = SS.map((r) => [r.model === "context" ? "Weibull + context CNN" : "Weibull + single-tower CNN", pc(r.target) + " %", r.n_runs, pc(r.recall_mean) + " +- " + pc(r.recall_sd), pc(r.recall_inshore_mean) + " +- " + pc(r.recall_inshore_sd), f2(r.FA_per_img_mean) + " +- " + f2(r.FA_per_img_sd), f3(r.F1_mean), "[" + pc(r.recall_boot_lo) + ", " + pc(r.recall_boot_hi) + "]", "[" + f2(r.FA_per_img_boot_lo) + ", " + f2(r.FA_per_img_boot_hi) + "]"]);
kids.push(table([3100, 1000, 700, 2200, 2200, 2100, 800, 1700, 1700], ["Network", "Val. retention target", "n", "Recall % (mean +- s.d.)", "Inshore recall % (mean +- s.d.)", "False events / img (mean +- s.d.)", "F1", "Run sd1: bootstrap 95 % CI, recall %", "Run sd1: bootstrap 95 % CI, FA / img"], T7, 15));
kids.push(note("Splits sp2 and sp3 hold out different images, so the s.d. includes split-to-split variation in the test set. Per-run values: Results/fixedpoint/seeds_all_runs.csv; s.d. over the three seeds of the original split only: seeds_summary.csv."));
kids.push(caption("Table 2c. Context network minus single-tower network, paired by run (same split and seed)."));
const T8 = SPR.map((r) => [pc(r.target) + " %", r.n_pairs, (100 * r.dRecall_mean).toFixed(2) + " (" + (100 * r.dRecall_min).toFixed(2) + " to " + (100 * r.dRecall_max).toFixed(2) + ")", (100 * r.dInshore_mean).toFixed(2), pc(r.FA_reduction_mean) + " (" + pc(r.FA_reduction_min) + " to " + pc(r.FA_reduction_max) + ")", r.ctx_fewer_FA_in + " of " + r.n_pairs]);
kids.push(table([1800, 800, 3800, 2400, 3800, 2200], ["Retention target", "Pairs", "Recall difference, points: mean (range)", "Inshore recall, points: mean", "False-event reduction %: mean (range)", "Runs with fewer false events"], T8, 15));
kids.push(P([B("What this changes in the earlier claim. "), "The single-run comparison suggested that the context network gains about two points of recall at equal false events. Over the runs the paired result is different and replaces it: at the validation-calibrated thresholds the two networks keep nearly the same fraction of ships (the context network is ahead by under one point on average and behind in some runs at the higher targets), while the context network produces fewer false events in every paired run, ", pc(SPR[1].FA_reduction_mean), " % fewer at the 95 % target and ", pc(SPR[2].FA_reduction_mean), " % fewer at the 97 % target on average. The context tower therefore buys precision at fixed recall, not recall at fixed false events. The run-to-run spread of recall at a fixed target is about one point (s.d.), larger than the recall difference between the two networks, so a recall difference cannot be claimed; the false-event difference can."]));

