// generated by gen_cnn_rtl_q4.py -- do not edit
localparam integer NL = 5;
localparam integer NIN = 32;
localparam integer BANK_DEPTH = 1152;
localparam integer AW = 11;
localparam integer WDEPTH = 2121;
localparam integer WAW = 12;
localparam integer PQDEPTH = 192;
localparam integer PQAW = 8;
localparam integer TW = 10;
localparam integer LANES_GEN = 32;
localparam integer WB_NIN = 16;
function integer L_K; input integer l; begin case (l)
    0: L_K = 5;
    1: L_K = 3;
    2: L_K = 3;
    3: L_K = 5;
    4: L_K = 1;
    default: L_K = 0; endcase end endfunction
function integer L_Cin; input integer l; begin case (l)
    0: L_Cin = 1;
    1: L_Cin = 16;
    2: L_Cin = 32;
    3: L_Cin = 32;
    4: L_Cin = 64;
    default: L_Cin = 0; endcase end endfunction
function integer L_Cout; input integer l; begin case (l)
    0: L_Cout = 16;
    1: L_Cout = 32;
    2: L_Cout = 32;
    3: L_Cout = 64;
    4: L_Cout = 1;
    default: L_Cout = 0; endcase end endfunction
function integer L_T; input integer l; begin case (l)
    0: L_T = 25;
    1: L_T = 144;
    2: L_T = 288;
    3: L_T = 800;
    4: L_T = 64;
    default: L_T = 0; endcase end endfunction
function integer L_G; input integer l; begin case (l)
    0: L_G = 1;
    1: L_G = 1;
    2: L_G = 1;
    3: L_G = 2;
    4: L_G = 1;
    default: L_G = 0; endcase end endfunction
function integer L_relu; input integer l; begin case (l)
    0: L_relu = 1;
    1: L_relu = 1;
    2: L_relu = 1;
    3: L_relu = 1;
    4: L_relu = 0;
    default: L_relu = 0; endcase end endfunction
function integer L_S; input integer l; begin case (l)
    0: L_S = 20;
    1: L_S = 23;
    2: L_S = 22;
    3: L_S = 23;
    4: L_S = 0;
    default: L_S = 0; endcase end endfunction
function integer L_WBASE; input integer l; begin case (l)
    0: L_WBASE = 0;
    1: L_WBASE = 25;
    2: L_WBASE = 169;
    3: L_WBASE = 457;
    4: L_WBASE = 2057;
    default: L_WBASE = 0; endcase end endfunction
function integer L_PBASE; input integer l; begin case (l)
    0: L_PBASE = 0;
    1: L_PBASE = 32;
    2: L_PBASE = 64;
    3: L_PBASE = 96;
    4: L_PBASE = 160;
    default: L_PBASE = 0; endcase end endfunction
function integer L_MODE; input integer l; begin case (l)
    0: L_MODE = 2;
    1: L_MODE = 1;
    2: L_MODE = 2;
    3: L_MODE = 0;
    4: L_MODE = 0;
    default: L_MODE = 0; endcase end endfunction
function integer L_QH; input integer l; begin case (l)
    0: L_QH = 14;
    1: L_QH = 6;
    2: L_QH = 5;
    3: L_QH = 1;
    4: L_QH = 1;
    default: L_QH = 0; endcase end endfunction
function integer L_QW; input integer l; begin case (l)
    0: L_QW = 14;
    1: L_QW = 6;
    2: L_QW = 5;
    3: L_QW = 1;
    4: L_QW = 1;
    default: L_QW = 0; endcase end endfunction
function integer L_WB_IN; input integer l; begin case (l)
    0: L_WB_IN = 16;
    1: L_WB_IN = 7;
    2: L_WB_IN = 6;
    3: L_WB_IN = 3;
    4: L_WB_IN = 1;
    default: L_WB_IN = 0; endcase end endfunction
function integer L_BSZ_IN; input integer l; begin case (l)
    0: L_BSZ_IN = 256;
    1: L_BSZ_IN = 49;
    2: L_BSZ_IN = 36;
    3: L_BSZ_IN = 9;
    4: L_BSZ_IN = 1;
    default: L_BSZ_IN = 0; endcase end endfunction
function integer L_WB_O; input integer l; begin case (l)
    0: L_WB_O = 7;
    1: L_WB_O = 6;
    2: L_WB_O = 3;
    3: L_WB_O = 1;
    4: L_WB_O = 1;
    default: L_WB_O = 0; endcase end endfunction
function integer L_BSZ_O; input integer l; begin case (l)
    0: L_BSZ_O = 49;
    1: L_BSZ_O = 36;
    2: L_BSZ_O = 9;
    3: L_BSZ_O = 1;
    4: L_BSZ_O = 1;
    default: L_BSZ_O = 0; endcase end endfunction
