// jtag_sys.v

// Generated using ACDS version 21.1 842

`timescale 1 ps / 1 ps
module jtag_sys (
		output wire [31:0] avm_address,       //   avm.address
		input  wire [31:0] avm_readdata,      //      .readdata
		output wire        avm_read,          //      .read
		output wire        avm_write,         //      .write
		output wire [31:0] avm_writedata,     //      .writedata
		input  wire        avm_waitrequest,   //      .waitrequest
		input  wire        avm_readdatavalid, //      .readdatavalid
		output wire [3:0]  avm_byteenable,    //      .byteenable
		input  wire        clk_clk,           //   clk.clk
		input  wire        reset_reset_n      // reset.reset_n
	);

	jtag_sys_jtag_master #(
		.USE_PLI     (0),
		.PLI_PORT    (50000),
		.FIFO_DEPTHS (2)
	) jtag_master (
		.clk_clk              (clk_clk),           //          clk.clk
		.clk_reset_reset      (~reset_reset_n),    //    clk_reset.reset
		.master_address       (avm_address),       //       master.address
		.master_readdata      (avm_readdata),      //             .readdata
		.master_read          (avm_read),          //             .read
		.master_write         (avm_write),         //             .write
		.master_writedata     (avm_writedata),     //             .writedata
		.master_waitrequest   (avm_waitrequest),   //             .waitrequest
		.master_readdatavalid (avm_readdatavalid), //             .readdatavalid
		.master_byteenable    (avm_byteenable),    //             .byteenable
		.master_reset_reset   ()                   // master_reset.reset
	);

endmodule
