function gen_frontend3_vectors()
%GEN_FRONTEND3_VECTORS  Golden pixel-in / expected-{c1,c2,c3} vectors for
%   front_end3_tb.v, generated by the SAME cfar_front_end_fixed.m used
%   throughout Phase 3 -- so the RTL is checked against the exact golden
%   model, not a re-derivation of it.
%
%   Only the INTERIOR region (>= TK_SLI from every edge) is compared: the
%   streaming line-buffer design does not produce a window at the border
%   (line_buffer.v's own header: "does not declare detections in the first/
%   last tsli rows/cols of a frame"), while cfar_front_end_fixed.m's
%   symmetric-padding box_sum_fixed computes a (different) value there. This
%   is an intentional, documented difference, not a bug -- comparing the
%   border would produce a false mismatch.

paths = cfar_setup();
sli = 17; guard = 13;
TK = (sli-1)/2;

rng(42);
% A small, real-image-derived test patch (not synthetic noise) -- SSDD image,
% cropped to keep simulation fast (a few thousand cycles, not millions).
imgs = dir(fullfile(paths.ssddJpeg, '*.jpg'));
Ifull = imread(fullfile(paths.ssddJpeg, imgs(37).name));
if ndims(Ifull) == 3, Ifull = rgb2gray(Ifull); end
IMG_H = 40; IMG_W = 48;
I = double(Ifull(1:IMG_H, 1:IMG_W));

fe = cfar_front_end_fixed(I, sli, guard, fullfile(paths.root,'lut','shared'));

outdir = fullfile(paths.root, 'rtl', 'common', 'tb');
if ~isfolder(outdir), mkdir(outdir); end

% ---- pixel stream, raster order, one 8-bit value per line -----------------
fid = fopen(fullfile(outdir, 'fe3_pixels.txt'), 'w');
for r = 1:IMG_H
    for c = 1:IMG_W
        fprintf(fid, '%d\n', I(r,c));
    end
end
fclose(fid);

% ---- expected outputs at every INTERIOR position, in raster order ---------
% Columns: row col c1_code c2_code c3_code x_code(centre, uncentred-domain
% code would need re-deriving; we instead re-check against xc code directly)
fid = fopen(fullfile(outdir, 'fe3_expected.txt'), 'w');
fprintf(fid, '%% row col c1_code c2_code c3_code\n');
for r = TK+1 : IMG_H-TK
    for c = TK+1 : IMG_W-TK
        fprintf(fid, '%d %d %d %d %d\n', r-1, c-1, fe.c1_code(r,c), fe.c2_code(r,c), fe.c3_code(r,c));
    end
end
fclose(fid);

fprintf('IMG_H=%d IMG_W=%d SLI=%d GUARD=%d TK=%d\n', IMG_H, IMG_W, sli, guard, TK);
fprintf('Wrote fe3_pixels.txt (%d pixels) and fe3_expected.txt (%d interior windows)\n', ...
    IMG_H*IMG_W, (IMG_H-2*TK)*(IMG_W-2*TK));
fprintf('Overflow counts: S1=%d S2=%d S3=%d c2=%d c3=%d\n', fe.Overflow.S1, fe.Overflow.S2, fe.Overflow.S3, fe.Overflow.c2, fe.Overflow.c3);
end
